### PR TITLE
Add Jenkinsfile

### PR DESCRIPTION
**Pull request by ultimaweapon**
This is the first step to integrate this repository to our new CI. What we will get from this PR is:

1. Automatically build & test for branches and PRs.

This PR not including CD when tags is created. That will come later around the beginning of March.

### CODE REVIEW

**Comment by ultimaweapon** [comment]
Once this PR is merged I will create users for everyone.

**Comment by riordant** [comment]
Concept ACK
How can this be tested?

**Comment by ultimaweapon** [comment]
I will create a user for you to take a look in Jenkins for build result.

**Comment by ultimaweapon** [comment]
@a-bezrukov could you please review this and merge it if there is no problems.

**Pull request merged**
