### PR TITLE
Merge master into sigma

### PR DESCRIPTION
**Pull request by ultimaweapon**

### CODE REVIEW

**Comment by ultimaweapon** [comment]
Integration tests still fail. Will fix it on Tuesday.

**Comment by nopslide** [comment]
This pull request **fixes 3 alerts** when merging 2f337b3c770915cb8f161525fb8065a7533eab67 into 19363356901abd8fbed98f6f5547d58e0a94e8eb - [view on LGTM.com](https://lgtm.com/projects/g/zcoinofficial/zcoin/rev/pr-ee53cf81ebae5b424789777145045dbf82be3cec)

**fixed alerts:**

* 3 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by nopslide** [comment]
This pull request **fixes 3 alerts** when merging 4fe8965fe8e0e9566e108cddef81d7241eb78cfa into 8a33b1378a6c91033025307d6d4b2a1f202894b8 - [view on LGTM.com](https://lgtm.com/projects/g/zcoinofficial/zcoin/rev/pr-24b00dd62a95df111f528172f6d7909c0ef516ae)

**fixed alerts:**

* 3 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by levonpetrosyan93** [comment]
Putta please fix conflicts.

**Comment by ultimaweapon** [comment]
@levonpetrosyan93 after discuss with @thebevrishot I think we don't need this fore the first release so I will fix it after the first release.

**Comment by nopslide** [comment]
This pull request **fixes 3 alerts** when merging 0241522536f561e0f4f425eede52936a085e88c6 into 8b7d49ef63387ab7b813ea95844369fb08995ef4 - [view on LGTM.com](https://lgtm.com/projects/g/zcoinofficial/zcoin/rev/pr-f21c5b95d59283a6ad9c7dcd8114605cb812f9d2)

**fixed alerts:**

* 3 for &#39;import \*&#39; may pollute namespace

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by nopslide** [comment]
This pull request **fixes 3 alerts** when merging 7fd1ba79872c3060b7253c751fcaa455a35816f9 into 8b7d49ef63387ab7b813ea95844369fb08995ef4 - [view on LGTM.com](https://lgtm.com/projects/g/zcoinofficial/zcoin/rev/pr-6a1e8087f53dc8bbda033dfa222696cc7b1d1f3e)

**fixed alerts:**

* 3 for &#39;import \*&#39; may pollute namespace

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ultimaweapon** [comment]
Seem like we need this before mainnet release otherwise the Zerocoin disable patch will not there.

**Comment by reubenyap** [comment]
Is this PR ready to be merged or anything outstanding?

**Comment by thebevrishot** [comment]
This one is ready to merge just but need two reviewers.

**Pull request merged**
