### PR TITLE
Updating Secp256k1 lib

### PR DESCRIPTION
**Pull request by levonpetrosyan93**

### CODE REVIEW

**Comment by ultimaweapon** [comment]
Do we still need this?

**Comment by levonpetrosyan93** [comment]
I think this is not a critical thing, we can decide what to do with this.

**Comment by reubenyap** [comment]
What is the background of this change again?

**Comment by levonpetrosyan93** [comment]
@reubenyap this is upgrading secp256k1 to upstream version, also some improvements in our wrappers suggested by @ultimaweapon, needs reviews and testing.

**Pull request closed without merging**
