### PR TITLE
Enabling ZSTD

### PR DESCRIPTION
**Pull request by levonpetrosyan93**

### CODE REVIEW

**Comment by ultimaweapon** [comment]
We don't need this anymore. When I was created #248 I don't know release get build, sorry for not updated the issue. If we really want to enable ZSTD for Tor we need to add it to `depends/packages` too, which I don't think it is worth.

**Comment by levonpetrosyan93** [comment]
@ultimaweapon In this PR ZSTD is being enabled when it is installed, I other cases it works as before.

**Comment by FreakyMaryk** [comment]
@Putta, could you pls approve that we need this changes which Levon did? Or we can just close this and not add this changes?

**Comment by reubenyap** [comment]
If this fixes when zstd is installed I don't see any harm in installing it.

**Comment by ultimaweapon** [comment]
What is the point to have it on developer machines but not in release? Currently it already disable ZSTD so even there is ZSTD installed in developer machines it will not try to use it.

**Comment by ultimaweapon** [comment]
@reubenyap the problems is it take some effort. If you think it worth to have it then we should include it with this PR.

**Pull request merged**
