### PR TITLE
Try to fix LGTM build failed

### PR DESCRIPTION
**Pull request by ultimaweapon**
The reason it fail is because it enable `libscrypt` for Tor but not apply linker flags when linking `zcoind`. See here for full logs: https://lgtm.com/projects/g/zcoinofficial/zcoin/logs/languages/lang:cpp

### CODE REVIEW

**Comment by riordant** [comment]
@ultimaweapon You know why CI failed?

**Comment by ultimaweapon** [comment]
@riordant we can ignore that one since it is build for branch. What we need just the `pr-merge` one.

**Comment by reubenyap** [comment]
Is this still needed @ultimaweapon ?

**Comment by ultimaweapon** [comment]
Yes. It will enable static code analysis.

**Comment by reubenyap** [comment]
Hi @ultimaweapon can you fix the build? Thanks!

**Comment by ultimaweapon** [comment]
@reubenyap if you mean one of failed CI we can ignore that. The only one that matter is `pr-merge` which is successfully.

**Comment by qashban4** [comment]
@riordant can we conclude this PR?

**Comment by riordant** [comment]
@qashban4 better to ask @ultimaweapon on that

**Comment by ultimaweapon** [comment]
Please take a look on my previous comments.

**Pull request merged**
