### PR TITLE
Postponing Sigma on testnet

### PR DESCRIPTION
**Pull request by a-bezrukov**

### CODE REVIEW

**Comment by ultimaweapon** [comment]
Do you have any reason why we need to do that?

**Comment by a-bezrukov** [comment]
To test ZC mints and spends

**Comment by ultimaweapon** [comment]
I see. If we want to do this way we need to allow previous Sigma mint but not new mints to be process by `CheckZerocoinTransactionV3` too otherwise the state will be incorrect. I think we have more better way. Instead we will remove Zerocoin transition code and allow Zerocoint until block 100,000 for testnet.

**Comment by ultimaweapon** [comment]
After discussion found out that we already deployed this patch and no any Sigma mint until current height. So we need to merge this.

**Comment by ultimaweapon** [comment]
After discussion we don't need this anymore.

**Pull request closed without merging**
