### PR TITLE
Optimize and Cleanup CScript::FindAndDelete

### PR DESCRIPTION
**Pull request by romanornr**
improves the worst-case behavior of CScript::FindAndDelete.
https://bitslog.wordpress.com/2017/01/08/a-bitcoin-transaction-that-takes-5-hours-to-verify/

### CODE REVIEW

**Comment by nopslide** [comment]
Does it fixed in 0.13 version in Bitcoin ?

**Comment by romanornr** [comment]
Bitcoin 0.13 is not effected.

Bitcoin Unlimited & Bitcoin Classic are effected.

**Comment by devwarrior777** [comment]
Hi Romano, 
Thanks for this PR and sorry no one acted on it for a while.

>"This vulnerability had an easy fix so I  reported it and it was quickly fixed in Bitcoin Core v0.12.1 (on 14 Apr). "

_From your linked article:_
As you know Zcoin is now on core 0.13.2+ and do not think that nodes with old code on 0.8 can run .. (I did not see any on the network for a while) Do you see any further vulnerability?

So do you think we can close this PR?
Thanks

**Comment by romanornr** [comment]
This PR can be closed for sure. 0.13+ is not effected.

**Pull request closed without merging**
