### PR TITLE
Genesis

### PR DESCRIPTION
**Pull request by DerUntote**
ok

### CODE REVIEW

**Comment by josescasanova** [comment]
Verticalcoin? whats going on?

**Comment by djm34** [comment]
lol... may-be time to learn the difference between a pull and clone

**Comment by reubenyap** [comment]
This is a clone attempt gone wrong.

**Comment by josescasanova** [comment]
@DerUntote why clone when you can add value to zcoin?

**Comment by DerUntote** [comment]
Sorry for stealing your time!

**Pull request closed without merging**
