### PR TITLE
Ignore auto-generated files and unit test binary

### PR DESCRIPTION
**Pull request by ultimaweapon**
- qa/pull-tester/run-bitcoind-for-test.sh
- qa/pull-tester/tests_config.py
- src/test/test_bitcoin

This also remove grouping in this file too. IMO grouping just added more complexity to edit this file. It will also introduce the possibility to have a duplicate entry too.

### CODE REVIEW

**Comment by a-bezrukov** [comment]
As the ignore list in the sorted order was not accepted by the team, I brought back the groupings.

**Comment by reubenyap** [comment]
Ping on this.

**Comment by ultimaweapon** [comment]
@reubenyap I will fix the conflict on next week.

**Comment by ultimaweapon** [comment]
We can close this PR now since master branch is already ignore those files.

**Pull request closed without merging**
