### PR TITLE
Unspent transaction outputs index

### PR DESCRIPTION
**Pull request by oti-dev**
Hello,

The intention of this contribution is to provide an efficient way to find out the current 'balance' of an arbitrary private key. 

Why do we need it:
The company I'm working for is manufacturing cryptocurrency ATMs and we find it useful to be able to verify if the customer actually has funds on his wallet. At the moment, the ATMs only support Bitcoin and Dash and we intend to add Zcoin as the third one.

What it does:
Based on existent 'chainstate'(CCoinsViewDB) database, a new database 'coinsbyscript' is created to aid retrieving a list of unspent transaction address for any given public address (or private key). From then on, the index is updated on each block connection/disconnection to provide first hand information at all times.

Credits:
 I'd like to mention that I'm not the sole author of the submitted code. It's basically my attempt to integrate Bitcoin's PR9806 ( https://github.com/bitcoin/bitcoin/pull/9806 ) into Zcoin project. I took the code from the bitcoin:PR9806, adapted it for use with zcoin's codebase, applied most important luke-jr's comments from his code review, and finally refactored the code to be more clear, simple and self-explanatory.

I hope you like the idea of adding this option to the codebase. If there's anything I can do to further simplify the merging process and/or upgrade the feature itself, let me know!

### CODE REVIEW

**Comment by reubenyap** [comment]
Thanks oti-dev! The devs are looking into it!

**Comment by oti-dev** [comment]
Update - the RPC now also returns the unconfirmed UTXOs (from mempool). It can be disabled by an input parameter. Also updated the RPC help message, which was incorrect before.

**Comment by aizensou** [comment]
Thanks again, oti-dev.
It looks very good. And awesome news as well. We will merge your request after the Znode HF running smooth. Merry Xmas.

**Comment by oti-dev** [comment]
That's great. :) I'm happy to contribute, and thank you for positive feedback.
Merry Xmas!

**Comment by reubenyap** [comment]
Given that Znodes is running smooth, it's time to relook into this.

**Comment by oti-dev** [comment]
Actually zcoin already has this functionality, it's been developped independently of this PQ and has been merged to master quite a while ago

**Comment by reubenyap** [comment]
Thank u oti-dev!

**Pull request closed without merging**
